# Generated by Django 5.2.8 on 2025-11-07 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_customuser_name_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={},
        ),
        migrations.RemoveField(
            model_name='incident',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('Harassment', 'Harassment'), ('Theft', 'Theft'), ('Lost', 'Lost'), ('Health', 'Health'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
