# Generated by Django 5.2.8 on 2025-11-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_incident_options_remove_incident_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('harassment', 'Harassment'), ('theft', 'Theft'), ('health', 'Health'), ('lost', 'Lost Item'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(default='open', max_length=32),
        ),
        migrations.AlterField(
            model_name='incident',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
