# Generated by Django 5.2.8 on 2025-11-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_incident_category_alter_incident_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General Inquiry'), ('emergency', 'Emergency Concern'), ('technical', 'Technical Support'), ('feedback', 'Feedback & Suggestions'), ('other', 'Other')], default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
